import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.output(18, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
GPIO.output(11, GPIO.LOW)
GPIO.output(12, GPIO.LOW)
motor1 = GPIO.PWM(15, 1000)
motor1.start(90)
motor2 = GPIO.PWM(22, 1000)
motor2.start(90)
GPIO.output(11, GPIO.HIGH)
GPIO.output(16, GPIO.HIGH)
time.sleep(5)
GPIO.output(11, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
#motor2.stop()
GPIO.output(12, GPIO.HIGH)
GPIO.output(18, GPIO.HIGH)
time.sleep(5)
GPIO.output(12, GPIO.LOW)
GPIO.output(18, GPIO.LOW)
